
# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:
  db:
    image: postgres:${VERSION}
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - sonarnet
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_DB=${DATABASE}
      - PG_DATA=/var/lib/postgresql/data
  
    volumes:
      - buildserver_pgdata:/var/lib/postgresql/data

    ports:
      - 5433:5432
 
  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - sonarnet
  
    ports:
      - "8112:8111"
    volumes:
    # - ./data:/data/teamcity_server/datadir
    # - ./logs:/opt/teamcity/logs
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs
  
    depends_on:
      - db

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - sonarnet
    privileged: true
    volumes:
      - ./agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
  teamcity-agent-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - sonarnet
    privileged: true
    volumes:
      - ./agents/agent-2/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
networks:
  sonarnet:
    driver: bridge
volumes:
 teamcity-data:
 teamcity-logs:
 buildserver_pgdata: